import clsx from 'clsx';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

import AuthSessionProvider from '../providers/authSessionProvider';
import AuthWatcher from '../components/authWatcher';
import Footer from '../components/Footer';
import { AppProvider } from '../components/Store';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(poppins.variable, 'antialiased')}>
        <AppProvider>
          <AuthSessionProvider>
            {children}
            {/* <Footer /> */}
            <AuthWatcher />
          </AuthSessionProvider>
        </AppProvider>
      </body>
    </html>
  );
}
